apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ithome.fullname" . }}
  labels:
    {{- include "ithome.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ithome.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ithome.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-ssl
          mountPath: /etc/nginx/conf.d/
        - name: nginx-include
          mountPath: /etc/nginx/conf.d/include
        - name: nginx-log
          mountPath: /var/log/nginx
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
