apiVersion: v1
kind: Service
metadata:
  name: {{ include "ithome.fullname" . }}
  labels:
    {{- include "ithome.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "ithome.selectorLabels" . | nindent 4 }}
  externalIPs:
    {{ .Values.service.externalIPs }}
